local mod = get_mod("PewPew")

mod.ENEMY_LINE_EFFECTS = {
	{ text="renegade_twin_captain_las_pistol_lasbeam" },
	{ text="renegade_lasbeam" },
	{ text="renegade_gunner_lasbeam" },
	{ text="renegade_sniper_lasbeam" },
	{ text="renegade_assault_lasbeam" },
	{ text="cultist_autogun_bullet" },
	{ text="renegade_heavy_stubber_bullet" },
	{ text="renegade_pellet" },
	{ text="renegade_captain_pellet" },
	{ text="renegade_captain_boltshell" },
	{ text="renegade_captain_plasma_beam" },
}

mod.melee_sound_effects_names = {
	--{ text="bot_combataxe_linesman", },
	--{ text="bot_combatsword_linesman_p1", },
	--{ text="bot_combatsword_linesman_p2", },
	{ text="chainaxe_p1_m1", },
	{ text="chainaxe_p1_m2", },
	{ text="chainsword_2h_p1_m1", },
	{ text="chainsword_2h_p1_m2", },
	{ text="chainsword_p1_m1", },
	{ text="chainsword_p1_m2", },
	{ text="combataxe_p1_m1", },
	{ text="combataxe_p1_m2", },
	{ text="combataxe_p1_m3", },
	{ text="combataxe_p2_m1", },
	{ text="combataxe_p2_m2", },
	{ text="combataxe_p2_m3", },
	{ text="combataxe_p3_m1", },
	{ text="combataxe_p3_m2", },
	{ text="combataxe_p3_m3", },
	{ text="combatknife_p1_m1", },
	{ text="combatknife_p1_m2", },
	{ text="combatsword_p1_m1", },
	{ text="combatsword_p1_m2", },
	{ text="combatsword_p1_m3", },
	{ text="combatsword_p2_m1", },
	{ text="combatsword_p2_m2", },
	{ text="combatsword_p2_m3", },
	{ text="combatsword_p3_m1", },
	{ text="combatsword_p3_m2", },
	{ text="combatsword_p3_m3", },
	{ text="forcesword_2h_p1_m1", },
	{ text="forcesword_2h_p1_m2", },
	{ text="forcesword_p1_m1", },
	{ text="forcesword_p1_m2", },
	{ text="forcesword_p1_m3", },
	{ text="ogryn_club_p1_m1", },
	{ text="ogryn_club_p1_m2", },
	{ text="ogryn_club_p1_m3", },
	{ text="ogryn_club_p2_m1", },
	{ text="ogryn_club_p2_m2", },
	{ text="ogryn_club_p2_m3", },
	{ text="ogryn_combatblade_p1_m1", },
	{ text="ogryn_combatblade_p1_m2", },
	{ text="ogryn_combatblade_p1_m3", },
	--{ text="ogryn_gauntlet_p1_m1", },
	{ text="ogryn_pickaxe_2h_p1_m1", },
	{ text="ogryn_pickaxe_2h_p1_m2", },
	{ text="ogryn_pickaxe_2h_p1_m3", },
	{ text="ogryn_powermaul_p1_m1", },
	{ text="ogryn_powermaul_slabshield_p1_m1", },
	--{ text="ogryn_thumper_p1_m1", },
	--{ text="ogryn_thumper_p1_m2", },
	{ text="powermaul_2h_p1_m1", },
	{ text="powermaul_p1_m1", },
	{ text="powermaul_p1_m2", },
	{ text="powermaul_p2_m1", },
	{ text="powermaul_p2_m2", },
	{ text="powermaul_shield_p1_m1", },
	{ text="powermaul_shield_p1_m2", },
	{ text="powersword_2h_p1_m1", },
	{ text="powersword_2h_p1_m2", },
	--{ text="powersword_2h_p1_m3", },
	{ text="powersword_p1_m1", },
	{ text="powersword_p1_m2", },
	--{ text="powersword_p1_m3", },
	{ text="thunderhammer_2h_p1_m1", },
	{ text="thunderhammer_2h_p1_m2", },
}

-- -------------------
-- Automatic Ranged Weapon Labels
-- -------------------
mod.automatic_weapon_labels = {
	"autopistol_p1_m1",
	"autogun_p1_m1",
	"autogun_p1_m2",
	"autogun_p1_m3",
	"autogun_p2_m1",
	"autogun_p2_m2",
	"autogun_p2_m3",
	"forcestaff_p2_m1",
	"forcestaff_p3_m1",
	"flamer_p1_m1",
	"lasgun_p3_m1",
	"lasgun_p3_m2",
	"lasgun_p3_m3",
	"ogryn_heavystubber_p1_m1",
	"ogryn_heavystubber_p1_m2",
	"ogryn_heavystubber_p1_m3",
	"ogryn_heavystubber_p2_m1",
	"ogryn_heavystubber_p2_m2",
	"ogryn_heavystubber_p2_m3",
}

-- -------------------
-- Semi-automatic
-- -------------------
mod.semiautomatic_weapon_labels = {
	"autogun_p3_m1",
	"autogun_p3_m2",
	"autogun_p3_m3",
	"bolter_p1_m1",
	-- "bolter_p1_m2", -- Unreleased
	-- "bolter_p1_m3", -- Unreleased
	"boltpistol_p1_m1",
	"forcestaff_p1_m1",
	"forcestaff_p4_m1",
	"lasgun_p1_m1",
	"lasgun_p1_m2",
	"lasgun_p1_m3",
	"lasgun_p2_m1",
	"lasgun_p2_m2",
	"lasgun_p2_m3",
	"laspistol_p1_m1",
	-- "laspistol_p1_m2", -- Unreleased
	"laspistol_p1_m3",
	"ogryn_gauntlet_p1_m1",
	"ogryn_thumper_p1_m1",
	"ogryn_thumper_p1_m2",
	-- "ogryn_thumper_p1_m3", -- Unreleased
	"ogryn_rippergun_p1_m1",
	"ogryn_rippergun_p1_m2",
	"ogryn_rippergun_p1_m3",
	"shotgun_p1_m1",
	"shotgun_p1_m2",
	"shotgun_p1_m3",
	"shotgun_p2_m1",
	"shotgun_p4_m1",
	"shotgun_p4_m2",
	"shotgun_p4_m3",
	"shotpistol_p1_m1",
	"stubrevolver_p1_m1",
	"stubrevolver_p1_m2",
	-- "stubrevolver_p1_m3", -- Unreleased
	"plasmagun_p1_m1",
	-- "plasmagun_p1_m2", -- Unreleased
}